name: Print GitHub data

on:
  push:
  pull_request:
  create:
  delete:
  release:

jobs:
  publishReleaseNotes:
    name: "Publish Release Notes - ${{ github.event_name }}"
    runs-on: ubuntu-22.04
    steps:
      - name: Publish Release Notes
        uses: webdeveric/publish-release-notes-action@309a52e059a3353b3a92312884066cf9938967b8

  printGitHubData:
    name: "Print GitHub data - ${{ github.event_name }}"
    runs-on: ubuntu-22.04
    steps:
      - name: Print GitHub data
        env:
          GITHUB_DATA: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_DATA"
