name: Print GitHub data

on: [push]

jobs:
  printGitHubData:
    name: Print GitHub data
    runs-on: ubuntu-22.04
    steps:
      - name: Print GitHub data
        env:
          GITHUB_DATA: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_DATA"
